# Policy apply example
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
  name: api-cat-fact-route
spec:
  targetRef:
    name: api
  policyRef:
    name: route
  config:
    destinationRef:
      name: cat-fact
  rules:
  # Forward /api/facts/cat => /facts
  - path: /api(/facts)/cat

