# How to setup a policy with config
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: PolicyBinding
metadata:
  name: message-logging
spec:
  targetRef:
    kind: Selector
    selector:
      kind: ApiInstance
      labels:
        policy/message-logging: "true"
  policyRef:
    name: message-logging-flex
  config:
    loggingConfiguration:
    - itemName: "request"
      itemData:
        message: "#[attributes.method ++ ' ' ++ attributes.requestPath ]"
        level: "INFO"
        firstSection: true
        secondSection: false
    - itemName: "response"
      itemData:
        message: "#[attributes.statusCode]"
        level: "INFO"
        firstSection: false
        secondSection: true
